pipeline {
    agent any
 
    environment {
         PATH_1 = 'C:/Windows/System32'
         PATH_2 = 'C:/Users/adama/Desktop/MSPR_ERP/flutter/bin'
         PATH_3 = 'C:/Program Files/Git/bin/git.exe'
         PATH_4 = 'C:/Program Files/Git/cmd'
    }

    stages{
        stage('Paytonkawa checkout') { 
            steps {
                git branch:'main',url:'https://github.com/fatoukine/PayTonKawa.git'
                }

        }

        stage('Paytonkawa clean') {
                steps {
                   dir ('PROJECT/'){
                    bat 'flutter clean'
                  }
                } 
         }

        stage('Paytonkawa dependencies') {
            steps {
               dir ('PROJECT/'){
                bat 'flutter pub get'
            }
          }  
        }

        stage('Paytonkawa test') {
            steps {
                dir('PROJECT/lib/'){
                       bat 'flutter test'
                    }
            }
        }

        stage('Paytonkawa package') {
              steps {
                  dir ('PROJECT/'){
                   bat 'flutter build apk --release'
                }
              }  
        }

        stage('Paytonkawa archive') {
            steps {
               dir ('PROJECT/'){
                bat 'mv build/app/outputs/flutter-apk/app-release.apk apk-payetonkawa-$BUILD_NUMBER.apk'
                archiveArtifacts artifacts: 'apk-payetonkawa-*.apk', followSymlinks: false

             }
          } 
        }  

    }
  }
